### ISSUE TITLE
i don't see any puppies.

### ISSUE THREAD

**Issue by rshorey** [heyitsolivia/secretpuppies#1]
There are no puppies on openpuppies.com

**Comment by heyitsolivia** [comment]
you're right, this needs fixin

**Comment by janrubio** [comment]
Confirmed absence of puppies on Internet Explorer. Please prioritize!

**Comment by heyitsolivia** [comment]
the absence of puppies on openpuppies.com should be resolved now

**Comment by rshorey** [comment]
great work, definitely resolved on ff/ubuntu
